### ISSUE TITLE
Question : Can be used headless?

### ISSUE THREAD

**Issue by 0x4139** [alexflint/gallium#6]
I am wondering if this can work headless if yes any documentation available?

**Comment by alexflint** [comment]
Not at the moment @0x4139 but I do know of projects that use chromium headless so I suspect this will eventually be possible. Out if interest, did you want headless mode because you wanted javascript/Go interop without a DOM, or because you wanted off-screen rendering for testing purposes, or something else?

**Comment by TingYiShun** [comment]
On an architectural level, the way we craft large-scale applications in JavaScript has changed in at least one fundamental way in the last few years. Once you remove the minutia of machinery bringing forth unidirectionaldata-binding,immutable data-structuresandvirtual-DOMl (some of which are interesting problem spaces) the one concept that many devs seem to have organically converged on iscomposition.
